// This code has been automatically generated by Maker Block Studio.
// Changes are overwritten whenever the blocks are edited.
// Last generated: 2026-08-07 10:18:44 UTC

// Includes
#include <Arduino.h>
#include "lumigame.h"
// End of includes

// Global declarations
int16_t vitesse = 0;
int8_t ledColor = 0;
int16_t active_led = 0;
int8_t phase = 0;
int point = 0;
int position = 0;
// End of global declarations

// Helper functions
void update_led()
{
  // Définit cette variable pour qu’elle soit égale à la valeur de l’entrée.
  ledColor = (255 * lumigameTimerRemaining("timer1")) / vitesse;
  // Définit la couleur de la LED à la position donnée. Prend effet au prochain tour de loop().
  setLedColor(active_led, CRGB(255 - ledColor, ledColor, 0));
}

void boucle()
{
  // Affiche une valeur sur le port série. 'print line' (println) ajoute un saut de ligne final.
  Serial.println("jeu 1 : Boucle Jeu");
  // Si la première valeur est vraie, alors exécuter le premier bloc d’instructions. Sinon, si la seconde valeur est vraie, exécuter le second bloc d’instructions.
  if (lumigameTimerExpired("timer1"))
  {
    // Fait défiler le texte sur la grille de LED, dans la couleur donnée, une colonne toutes les X millisecondes. Appelle ce bloc à chaque tour de loop() (avec le même texte) pour que le défilement continue - il garde sa position en mémoire et recommence depuis le début une fois sorti complètement de l'écran.
    lumigameScrollText("GAME OVER ", CRGB::Red, 250);
    // Définit cette variable pour qu’elle soit égale à la valeur de l’entrée.
    phase = 1;
  }
  else if ((getButtonState(active_led) == true))
  {
    // Définit cette variable pour qu’elle soit égale à la valeur de l’entrée.
    point = point + 10;
    // Définit la couleur de la LED à la position donnée. Prend effet au prochain tour de loop().
    setLedColor(active_led, CRGB::Black);
    // Essaie toutes les positions de bouton dans un ordre aléatoire, en exposant chaque candidate via une variable. « valide si » décide si elle est retenue - elle est valide par défaut, sauf si un bloc « retourner » à l'intérieur la met à false (par ex. pour exiger une LED éteinte). La première position valide déclenche « si trouvée » ; si aucune des 32 positions n'est valide, c'est « si aucune trouvée » qui s'exécute.
    {
      uint8_t candidates[NUM_BUTTONS];
      shuffledPositions(candidates);
      bool found = false;
      for (uint8_t idx = 0; idx < NUM_BUTTONS && !found; idx++)
      {
        uint8_t position = candidates[idx];
        bool valid = [&]() -> bool
        {
          return true;
        }();
        if (valid)
        {
          found = true;
          // Définit cette variable pour qu’elle soit égale à la valeur de l’entrée.
          active_led = position;
        }
      }
      if (!found)
      {
      }
    }

    // Définit cette variable pour qu’elle soit égale à la valeur de l’entrée.
    vitesse = vitesse - 100;
    // (Re)démarre le minuteur nommé pour qu'il expire dans le nombre de millisecondes donné. Les minuteurs sont identifiés par leur nom, donc plusieurs minuteurs indépendants peuvent tourner en même temps.
    lumigameTimerSet("timer1", vitesse);
  }
  // Appelle une fonction.
  update_led();
}

void game_over()
{
  // Affiche une valeur sur le port série. 'print line' (println) ajoute un saut de ligne final.
  Serial.println("jeu 1 : Score");
  // Fait défiler le texte sur la grille de LED, dans la couleur donnée, une colonne toutes les X millisecondes. Appelle ce bloc à chaque tour de loop() (avec le même texte) pour que le défilement continue - il garde sa position en mémoire et recommence depuis le début une fois sorti complètement de l'écran.
  lumigameScrollText("", CRGB::Red, 250);
  // Si une valeur est vraie, alors exécuter certaines instructions.
  if (lumigameScrollTextFinished())
  {
    // Fait défiler le texte sur la grille de LED, dans la couleur donnée, une colonne toutes les X millisecondes. Appelle ce bloc à chaque tour de loop() (avec le même texte) pour que le défilement continue - il garde sa position en mémoire et recommence depuis le début une fois sorti complètement de l'écran.
    lumigameScrollText(String(point), CRGB::Red, 600);
    // Définit cette variable pour qu’elle soit égale à la valeur de l’entrée.
    phase = 2;
  }
}

void score()
{
  // Affiche une valeur sur le port série. 'print line' (println) ajoute un saut de ligne final.
  Serial.println("jeu 1 : Score");
  // Fait défiler le texte sur la grille de LED, dans la couleur donnée, une colonne toutes les X millisecondes. Appelle ce bloc à chaque tour de loop() (avec le même texte) pour que le défilement continue - il garde sa position en mémoire et recommence depuis le début une fois sorti complètement de l'écran.
  lumigameScrollText("", CRGB::Red, 600);
  // Si une valeur est vraie, alors exécuter certaines instructions.
  if (lumigameScrollTextFinished())
  {
    // Définit cette variable pour qu’elle soit égale à la valeur de l’entrée.
    phase = 3;
  }
}

void jeu1_start()
{
  // Initialise la communication série au débit en bauds donné. Placer dans un bloc 'setup' pour l'exécuter une seule fois au démarrage.
  Serial.begin(115200);
  // Affiche une valeur sur le port série. 'print line' (println) ajoute un saut de ligne final.
  Serial.println("jeu 1 : Début");
  // Définit cette variable pour qu’elle soit égale à la valeur de l’entrée.
  phase = 0;
  // Met les 32 LED à la même couleur. Prend effet au prochain tour de loop().
  setAllLeds(CRGB::Black);
  // Essaie toutes les positions de bouton dans un ordre aléatoire, en exposant chaque candidate via une variable. « valide si » décide si elle est retenue - elle est valide par défaut, sauf si un bloc « retourner » à l'intérieur la met à false (par ex. pour exiger une LED éteinte). La première position valide déclenche « si trouvée » ; si aucune des 32 positions n'est valide, c'est « si aucune trouvée » qui s'exécute.
  {
    uint8_t candidates[NUM_BUTTONS];
    shuffledPositions(candidates);
    bool found = false;
    for (uint8_t idx = 0; idx < NUM_BUTTONS && !found; idx++)
    {
      uint8_t position = candidates[idx];
      bool valid = [&]() -> bool
      {
        return true;
      }();
      if (valid)
      {
        found = true;
        // Définit cette variable pour qu’elle soit égale à la valeur de l’entrée.
        active_led = position;
      }
    }
    if (!found)
    {
    }
  }

  // Définit cette variable pour qu’elle soit égale à la valeur de l’entrée.
  vitesse = 5000;
  // (Re)démarre le minuteur nommé pour qu'il expire dans le nombre de millisecondes donné. Les minuteurs sont identifiés par leur nom, donc plusieurs minuteurs indépendants peuvent tourner en même temps.
  lumigameTimerSet("timer1", vitesse);
  // Définit cette variable pour qu’elle soit égale à la valeur de l’entrée.
  point = 0;
  // Appelle une fonction.
  update_led();
}

uint8_t jeu1_loop()
{
  // Affiche une valeur sur le port série. 'print line' (println) ajoute un saut de ligne final.
  Serial.println("jeu 1 : Boucle");
  // Affiche une valeur sur le port série. 'print line' (println) ajoute un saut de ligne final.
  Serial.println(phase);
  // Aiguillage (switch) sur une expression. Utilisez [+] pour ajouter des cas et [−] pour les supprimer.
  switch (phase)
  {
  case 0:
    // Appelle une fonction.
    boucle();
    break;
  case 1:
    // Appelle une fonction.
    game_over();
    break;
  case 2:
    // Appelle une fonction.
    score();
    break;
  case 3:
    // Termine immédiatement la partie en cours et revient au menu. À placer dans le bloc boucle d'un jeu.
    return -1;
    break;
  }
  return 0;
}

void jeu1_stop()
{
}

// End of helper functions
