// This code has been automatically generated by Maker Block Studio.
// Changes are overwritten whenever the blocks are edited.
// Last generated: 2026-08-06 21:54:11 UTC

// Includes
#include <Arduino.h>
#include "lumigame.h"
// End of includes

// Global declarations
int position = 0;
// End of global declarations

// Helper functions
void jeu1_start()
{
}

uint8_t jeu1_loop()
{
  // Répète les blocs contenus une fois pour chaque position de bouton (0-31), la position courante étant disponible via une variable.
  for (uint8_t position = 0; position < NUM_BUTTONS; position++)
  {
    // Si une valeur est vraie, alors exécuter certaines instructions.
    if ((getButtonState(position) == true))
    {
      // Définit la couleur de la LED à la position donnée. Prend effet au prochain tour de loop().
      setLedColor(position, CRGB(255, 0, 0));
    }
  }
  return 0;
}

void jeu1_stop()
{
}

// End of helper functions
