// This code has been automatically generated by Maker Block Studio.
// Changes are overwritten whenever the blocks are edited.
// Last generated: 2026-08-18 00:18:45 UTC

// Includes
#include <Arduino.h>
#include "lumigame.h"
// End of includes

// Global declarations
#define PHASE_CHOIX_NB_JOUEURS 0
#define PHASE_BOUCLE 1
#define PHASE_GAME_OVER 2
#define PHASE_SCORE 3
#define PHASE_EXIT 4
#define VITESSE_DEFAULT 5000
#define VITESSE_DELTA 100
static uint8_t phase = 0;
static int8_t nb_joueurs = 0;
static int8_t nb_joueur_restant = 0;
static uint32_t zones[4] = {};
static int32_t couleurs[4] = {};
static uint16_t scores[4] = {};
static uint8_t positions[4] = {};
static int16_t vitesses[4] = {};
static int8_t gagnant = 0;
static uint8_t joueur = 0;
static uint8_t position = 0;
// End of global declarations

// Function prototypes
static void affiche_menu();
static void init_games();
static void choix_nb_joueur();
static void boucle();
static void game_over();
// End of function prototypes

// Helper functions
static void affiche_menu()
{
    // Met les 32 LED à la même couleur. Prend effet au prochain tour de loop().
    setAllLeds(CRGB::Black);
    // Faire prendre successivement à la variable « i » les valeurs entre le nombre du début et celui de fin en incrémentant du pas spécifié et exécuter les instructions spécifiées.
    for (int i = 1; i <= 3; i += 1)
    {
        // Définit la couleur de la LED à la position donnée. Prend effet au prochain tour de loop().
        setLedColor((((uint8_t)(0) * NUM_COLS) + (uint8_t)(i)), (i + nb_joueurs != -1 ? CRGB::White : CRGB::Blue));
    }
}

static void init_games()
{
    // Aiguillage (switch) sur une expression. Utilisez [+] pour ajouter des cas et [−] pour les supprimer.
    switch (nb_joueurs)
    {
    case 2:
        // Définit un élément d'un tableau par index.
        zones[0] = lumigameZoneMask({1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0});
        // Définit un élément d'un tableau par index.
        zones[1] = lumigameZoneMask({0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1});
        break;
    case 3:
        // Définit un élément d'un tableau par index.
        zones[0] = lumigameZoneMask({1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0});
        // Définit un élément d'un tableau par index.
        zones[1] = lumigameZoneMask({0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0});
        // Définit un élément d'un tableau par index.
        zones[2] = lumigameZoneMask({0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1});
        break;
    case 4:
        // Définit un élément d'un tableau par index.
        zones[0] = lumigameZoneMask({1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0});
        // Définit un élément d'un tableau par index.
        zones[1] = lumigameZoneMask({0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0});
        // Définit un élément d'un tableau par index.
        zones[2] = lumigameZoneMask({0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0});
        // Définit un élément d'un tableau par index.
        zones[3] = lumigameZoneMask({0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1});
        break;
    }
    // Faire prendre successivement à la variable « joueur » les valeurs entre le nombre du début et celui de fin en incrémentant du pas spécifié et exécuter les instructions spécifiées.
    for (int joueur = 0; joueur <= nb_joueurs - 1; joueur += 1)
    {
        // Définit un élément d'un tableau par index.
        scores[joueur] = 0;
        // Essaie toutes les positions de bouton dans un ordre aléatoire, en exposant chaque candidate via une variable. « valide si » est une expression booléenne qui décide si elle est retenue (vrai par défaut si laissé vide). La première position valide déclenche « si trouvée » ; si aucune des 32 positions n'est valide, c'est « si aucune trouvée » qui s'exécute.
        {
            uint8_t candidates[NUM_BUTTONS];
            shuffledPositions(candidates);
            bool found = false;
            for (uint8_t idx = 0; idx < NUM_BUTTONS && !found; idx++)
            {
                uint8_t position = candidates[idx];
                bool valid = (lumigamePositionInZone(position, zones[joueur]));
                if (valid)
                {
                    found = true;
                    // Définit un élément d'un tableau par index.
                    positions[joueur] = position;
                    // Définit la couleur de la LED à la position donnée. Prend effet au prochain tour de loop().
                    setLedColor(position, couleurs[joueur]);
                }
            }
            if (!found)
            {
            }
        }
    }
    // Faire prendre successivement à la variable « joueur » les valeurs entre le nombre du début et celui de fin en incrémentant du pas spécifié et exécuter les instructions spécifiées.
    for (int joueur = 0; joueur <= nb_joueurs - 1; joueur += 1)
    {
        // Définit un élément d'un tableau par index.
        vitesses[joueur] = VITESSE_DEFAULT;
        // (Re)démarre le minuteur INDEX (0-15) pour qu'il expire dans le nombre de millisecondes donné. Chaque index tourne indépendamment, donc plusieurs minuteurs peuvent être actifs en même temps.
        lumigameTimerSet(joueur, VITESSE_DEFAULT);
    }
}

static void choix_nb_joueur()
{
    // Si la première valeur est vraie, alors exécuter le premier bloc d’instructions. Sinon, si la seconde valeur est vraie, exécuter le second bloc d’instructions.
    if (nb_joueurs == 0)
    {
        // Définit cette variable pour qu’elle soit égale à la valeur de l’entrée.
        nb_joueurs = -1;
        // Appelle une fonction.
        affiche_menu();
    }
    else if (lumigameIsScrollingText())
    {
        // Fait défiler le texte sur la grille de LED, dans la couleur donnée, une colonne toutes les X millisecondes. Appelle ce bloc à chaque tour de loop() pour que le défilement continue - il garde sa position en mémoire et recommence depuis le début une fois sorti complètement de l'écran. Laisse « texte » vide (sa valeur par défaut) une fois le message déjà défini, pour continuer à le faire défiler sans avoir à le recalculer/rebrancher à chaque frame - utilise « interrompre l'affichage du texte » pour vraiment l'effacer.
        lumigameScrollText("", CRGB(255, 255, 255), 300);
        // Si une valeur est vraie, alors exécuter certaines instructions.
        if (lumigameScrollTextFinished())
        {
            // Appelle une fonction.
            affiche_menu();
        }
    }
    // Faire prendre successivement à la variable « i » les valeurs entre le nombre du début et celui de fin en incrémentant du pas spécifié et exécuter les instructions spécifiées.
    for (int i = 1; i <= 3; i += 1)
    {
        // Si une valeur est vraie, alors exécuter certaines instructions.
        if (queryButtonState((((uint8_t)(0) * NUM_COLS) + (uint8_t)(i)), BUTTON_JUST_PRESSED))
        {
            // Si une valeur est vraie, alors exécuter le premier bloc d’instructions. Sinon, exécuter le second bloc d’instructions.
            if (i + nb_joueurs == -1)
            {
                // Définit cette variable pour qu’elle soit égale à la valeur de l’entrée.
                nb_joueurs = 1 + i;
                // Définit cette variable pour qu’elle soit égale à la valeur de l’entrée.
                nb_joueur_restant = nb_joueurs;
                // Met les 32 LED à la même couleur. Prend effet au prochain tour de loop().
                setAllLeds(CRGB::Black);
                // Appelle une fonction.
                init_games();
                // Définit cette variable pour qu’elle soit égale à la valeur de l’entrée.
                phase = PHASE_BOUCLE;
            }
            else
            {
                // Définit cette variable pour qu’elle soit égale à la valeur de l’entrée.
                nb_joueurs = -1 - i;
                // Fait défiler le texte sur la grille de LED, dans la couleur donnée, une colonne toutes les X millisecondes. Appelle ce bloc à chaque tour de loop() pour que le défilement continue - il garde sa position en mémoire et recommence depuis le début une fois sorti complètement de l'écran. Laisse « texte » vide (sa valeur par défaut) une fois le message déjà défini, pour continuer à le faire défiler sans avoir à le recalculer/rebrancher à chaque frame - utilise « interrompre l'affichage du texte » pour vraiment l'effacer.
                lumigameScrollText(String(0 - nb_joueurs), CRGB::White, 300);
            }
        }
    }
}

static void boucle()
{
    // Faire prendre successivement à la variable « joueur » les valeurs entre le nombre du début et celui de fin en incrémentant du pas spécifié et exécuter les instructions spécifiées.
    for (int joueur = 0; joueur <= nb_joueurs - 1; joueur += 1)
    {
        // Si la première valeur est vraie, alors exécuter le premier bloc d’instructions. Sinon, si la seconde valeur est vraie, exécuter le second bloc d’instruction. Si aucune des valeurs n’est vraie, exécuter le dernier bloc d’instruction.
        if (vitesses[joueur] < 0)
        {
            // Sauter le reste de cette boucle, et poursuivre avec l’itération suivante.
            continue;
        }
        else if (lumigameTimerExpired(joueur))
        {
            // Définit un élément d'un tableau par index.
            vitesses[joueur] = -1;
            // Répète les blocs contenus une fois pour chaque position de bouton (0-31), la position courante étant disponible via une variable.
            for (uint8_t position = 0; position < NUM_BUTTONS; position++)
            {
                // Si une valeur est vraie, alors exécuter certaines instructions.
                if (lumigamePositionInZone(position, zones[joueur]))
                {
                    // Définit la couleur de la LED à la position donnée. Prend effet au prochain tour de loop().
                    setLedColor(position, CRGB::Red);
                }
            }

            // Définit cette variable pour qu’elle soit égale à la valeur de l’entrée.
            nb_joueur_restant = nb_joueur_restant - 1;
        }
        else if (queryButtonState(positions[joueur], BUTTON_PRESSED))
        {
            // Faire prendre successivement à la variable « joueur_autre » les valeurs entre le nombre du début et celui de fin en incrémentant du pas spécifié et exécuter les instructions spécifiées.
            for (int joueur_autre = 0; joueur_autre <= nb_joueurs - 1; joueur_autre += 1)
            {
                // Si la première valeur est vraie, alors exécuter le premier bloc d’instructions. Sinon, si la seconde valeur est vraie, exécuter le second bloc d’instruction. Si aucune des valeurs n’est vraie, exécuter le dernier bloc d’instruction.
                if (vitesses[joueur_autre] < 0)
                {
                    // Sauter le reste de cette boucle, et poursuivre avec l’itération suivante.
                    continue;
                }
                else if (joueur_autre == joueur)
                {
                    // Définit un élément d'un tableau par index.
                    vitesses[joueur] = vitesses[joueur] + VITESSE_DELTA * (nb_joueur_restant - 2);
                }
                else if (vitesses[joueur_autre] > VITESSE_DELTA)
                {
                    // Définit un élément d'un tableau par index.
                    vitesses[joueur_autre] = vitesses[joueur_autre] - VITESSE_DELTA;
                }
                else
                {
                    // Définit un élément d'un tableau par index.
                    vitesses[joueur_autre] = 0;
                }
                // Définit la couleur de la LED à la position donnée. Prend effet au prochain tour de loop().
                setLedColor(positions[joueur], CRGB::Black);
                // Essaie toutes les positions de bouton dans un ordre aléatoire, en exposant chaque candidate via une variable. « valide si » est une expression booléenne qui décide si elle est retenue (vrai par défaut si laissé vide). La première position valide déclenche « si trouvée » ; si aucune des 32 positions n'est valide, c'est « si aucune trouvée » qui s'exécute.
                {
                    uint8_t candidates[NUM_BUTTONS];
                    shuffledPositions(candidates);
                    bool found = false;
                    for (uint8_t idx = 0; idx < NUM_BUTTONS && !found; idx++)
                    {
                        uint8_t position = candidates[idx];
                        bool valid = (lumigamePositionInZone(position, zones[joueur]));
                        if (valid)
                        {
                            found = true;
                            // Définit un élément d'un tableau par index.
                            positions[joueur] = position;
                            // Définit la couleur de la LED à la position donnée. Prend effet au prochain tour de loop().
                            setLedColor(position, couleurs[joueur]);
                            // (Re)démarre le minuteur INDEX (0-15) pour qu'il expire dans le nombre de millisecondes donné. Chaque index tourne indépendamment, donc plusieurs minuteurs peuvent être actifs en même temps.
                            lumigameTimerSet(joueur, vitesses[joueur]);
                        }
                    }
                    if (!found)
                    {
                    }
                }
            }
        }
        else
        {
            // Déclare une variable avec un type explicite (modifiable). Placé à l'intérieur d'une fonction ou de Setup, c'est une variable locale — cochez « static » pour conserver sa valeur entre les appels. Placé hors de toute fonction (par ex. seul dans un fichier secondaire), c'est une déclaration au niveau du fichier à la place.
            uint32_t ledColor = 0;
            // Définit cette variable pour qu’elle soit égale à la valeur de l’entrée.
            ledColor = (uint32_t)(lumigameDimColor(couleurs[joueur], (255 * lumigameTimerRemaining(joueur)) / vitesses[joueur]));
            // Définit la couleur de la LED à la position donnée. Prend effet au prochain tour de loop().
            setLedColor(positions[joueur], ledColor);
        }
    }
    // Si une valeur est vraie, alors exécuter certaines instructions.
    if (nb_joueur_restant <= 1)
    {
        // Définit cette variable pour qu’elle soit égale à la valeur de l’entrée.
        phase = PHASE_GAME_OVER;
        // Faire prendre successivement à la variable « joueur » les valeurs entre le nombre du début et celui de fin en incrémentant du pas spécifié et exécuter les instructions spécifiées.
        for (int joueur = 0; joueur <= nb_joueurs - 1; joueur += 1)
        {
            // Si une valeur est vraie, alors exécuter certaines instructions.
            if (vitesses[joueur] > 0)
            {
                // Répète les blocs contenus une fois pour chaque position de bouton (0-31), la position courante étant disponible via une variable.
                for (uint8_t position = 0; position < NUM_BUTTONS; position++)
                {
                    // Si une valeur est vraie, alors exécuter certaines instructions.
                    if (lumigamePositionInZone(position, zones[joueur]))
                    {
                        // Définit la couleur de la LED à la position donnée. Prend effet au prochain tour de loop().
                        setLedColor(position, CRGB::Green);
                    }
                }
            }
        }
        // (Re)démarre le minuteur INDEX (0-15) pour qu'il expire dans le nombre de millisecondes donné. Chaque index tourne indépendamment, donc plusieurs minuteurs peuvent être actifs en même temps.
        lumigameTimerSet(0, 5000);
    }
}

static void game_over()
{
    // Si une valeur est vraie, alors exécuter certaines instructions.
    if (lumigameTimerExpired(0))
    {
        // Définit cette variable pour qu’elle soit égale à la valeur de l’entrée.
        phase = PHASE_EXIT;
    }
}

void jeu_duel_start()
{
    // Initialise la communication série au débit en bauds donné. Placer dans un bloc 'setup' pour l'exécuter une seule fois au démarrage.
    Serial.begin(115200);
    // Définit un élément d'un tableau par index.
    couleurs[0] = CRGB::Red;
    // Définit un élément d'un tableau par index.
    couleurs[1] = CRGB::Blue;
    // Définit un élément d'un tableau par index.
    couleurs[2] = CRGB::Lime;
    // Définit un élément d'un tableau par index.
    couleurs[3] = CRGB::Magenta;
    // Définit cette variable pour qu’elle soit égale à la valeur de l’entrée.
    phase = PHASE_CHOIX_NB_JOUEURS;
    // Définit cette variable pour qu’elle soit égale à la valeur de l’entrée.
    nb_joueurs = 0;
}

uint8_t jeu_duel_loop()
{
    // Aiguillage (switch) sur une expression. Utilisez [+] pour ajouter des cas et [−] pour les supprimer.
    switch (phase)
    {
    case PHASE_CHOIX_NB_JOUEURS:
        // Appelle une fonction.
        choix_nb_joueur();
        break;
    case PHASE_BOUCLE:
        // Appelle une fonction.
        boucle();
        break;
    case PHASE_GAME_OVER:
        // Appelle une fonction.
        game_over();
        break;
    case PHASE_EXIT:
        // Termine immédiatement la partie en cours et revient au menu. À placer dans le bloc boucle d'un jeu.
        return -1;
        break;
    }
    return 0;
}

void jeu_duel_stop()
{
}

// End of helper functions
