// This code has been automatically generated by Maker Block Studio.
// Changes are overwritten whenever the blocks are edited.
// Last generated: 2026-08-17 22:51:12 UTC

// Includes
#include <Arduino.h>
#include "lumigame.h"
// End of includes

// Global declarations
#define PHASE_BOUCLE 0
#define PHASE_GAME_OVER 1
#define PHASE_SCORE 2
#define PHASE_EXIT 3
#define TIMER 0
static int point = 0;
static int16_t vitesse = 0;
static uint16_t active_led = 0;
static uint8_t phase = 0;
// End of global declarations

// Function prototypes
static void update_led();
static void boucle();
static void game_over();
static void score();
// End of function prototypes

// Helper functions
static void update_led()
{
  // Déclare une variable avec un type explicite (modifiable). Placé à l'intérieur d'une fonction ou de Setup, c'est une variable locale — cochez « static » pour conserver sa valeur entre les appels. Placé hors de toute fonction (par ex. seul dans un fichier secondaire), c'est une déclaration au niveau du fichier à la place.
  int8_t ledColor = 0;
  // Définit cette variable pour qu’elle soit égale à la valeur de l’entrée.
  ledColor = (255 * lumigameTimerRemaining(0)) / vitesse;
  // Définit la couleur de la LED à la position donnée. Prend effet au prochain tour de loop().
  setLedColor(active_led, CRGB(255 - ledColor, ledColor, 0));
}

static void boucle()
{
  // Affiche une valeur sur le port série. 'print line' (println) ajoute un saut de ligne final.
  Serial.println("jeu 1 : Boucle Jeu");
  // Si la première valeur est vraie, alors exécuter le premier bloc d’instructions. Sinon, si la seconde valeur est vraie, exécuter le second bloc d’instructions.
  if (lumigameTimerExpired(TIMER))
  {
    // Fait défiler le texte sur la grille de LED, dans la couleur donnée, une colonne toutes les X millisecondes. Appelle ce bloc à chaque tour de loop() pour que le défilement continue - il garde sa position en mémoire et recommence depuis le début une fois sorti complètement de l'écran. Laisse « texte » vide (sa valeur par défaut) une fois le message déjà défini, pour continuer à le faire défiler sans avoir à le recalculer/rebrancher à chaque frame - utilise « interrompre l'affichage du texte » pour vraiment l'effacer.
    lumigameScrollText("GAME OVER ", CRGB::Red, 250);
    // Définit cette variable pour qu’elle soit égale à la valeur de l’entrée.
    phase = PHASE_GAME_OVER;
  }
  else if (queryButtonState(active_led, BUTTON_PRESSED))
  {
    // Définit cette variable pour qu’elle soit égale à la valeur de l’entrée.
    point = point + 10;
    // Définit la couleur de la LED à la position donnée. Prend effet au prochain tour de loop().
    setLedColor(active_led, CRGB::Black);
    // Essaie toutes les positions de bouton dans un ordre aléatoire, en exposant chaque candidate via une variable. « valide si » est une expression booléenne qui décide si elle est retenue (vrai par défaut si laissé vide). La première position valide déclenche « si trouvée » ; si aucune des 32 positions n'est valide, c'est « si aucune trouvée » qui s'exécute.
    {
      uint8_t candidates[NUM_BUTTONS];
      shuffledPositions(candidates);
      bool found = false;
      for (uint8_t idx = 0; idx < NUM_BUTTONS && !found; idx++)
      {
        uint8_t position = candidates[idx];
        bool valid = (true);
        if (valid)
        {
          found = true;
          // Définit cette variable pour qu’elle soit égale à la valeur de l’entrée.
          active_led = position;
        }
      }
      if (!found)
      {
      }
    }

    // Définit cette variable pour qu’elle soit égale à la valeur de l’entrée.
    vitesse = vitesse - 100;
    // (Re)démarre le minuteur INDEX (0-15) pour qu'il expire dans le nombre de millisecondes donné. Chaque index tourne indépendamment, donc plusieurs minuteurs peuvent être actifs en même temps.
    lumigameTimerSet(TIMER, vitesse);
  }
  // Appelle une fonction.
  update_led();
}

static void game_over()
{
  // Affiche une valeur sur le port série. 'print line' (println) ajoute un saut de ligne final.
  Serial.println("jeu 1 : Score");
  // Fait défiler le texte sur la grille de LED, dans la couleur donnée, une colonne toutes les X millisecondes. Appelle ce bloc à chaque tour de loop() pour que le défilement continue - il garde sa position en mémoire et recommence depuis le début une fois sorti complètement de l'écran. Laisse « texte » vide (sa valeur par défaut) une fois le message déjà défini, pour continuer à le faire défiler sans avoir à le recalculer/rebrancher à chaque frame - utilise « interrompre l'affichage du texte » pour vraiment l'effacer.
  lumigameScrollText("", CRGB::Red, 250);
  // Si une valeur est vraie, alors exécuter certaines instructions.
  if (lumigameScrollTextFinished())
  {
    // Fait défiler le texte sur la grille de LED, dans la couleur donnée, une colonne toutes les X millisecondes. Appelle ce bloc à chaque tour de loop() pour que le défilement continue - il garde sa position en mémoire et recommence depuis le début une fois sorti complètement de l'écran. Laisse « texte » vide (sa valeur par défaut) une fois le message déjà défini, pour continuer à le faire défiler sans avoir à le recalculer/rebrancher à chaque frame - utilise « interrompre l'affichage du texte » pour vraiment l'effacer.
    lumigameScrollText(String(point), CRGB::Red, 600);
    // Définit cette variable pour qu’elle soit égale à la valeur de l’entrée.
    phase = PHASE_SCORE;
  }
}

static void score()
{
  // Affiche une valeur sur le port série. 'print line' (println) ajoute un saut de ligne final.
  Serial.println("jeu 1 : Score");
  // Fait défiler le texte sur la grille de LED, dans la couleur donnée, une colonne toutes les X millisecondes. Appelle ce bloc à chaque tour de loop() pour que le défilement continue - il garde sa position en mémoire et recommence depuis le début une fois sorti complètement de l'écran. Laisse « texte » vide (sa valeur par défaut) une fois le message déjà défini, pour continuer à le faire défiler sans avoir à le recalculer/rebrancher à chaque frame - utilise « interrompre l'affichage du texte » pour vraiment l'effacer.
  lumigameScrollText("", CRGB::Red, 600);
  // Si une valeur est vraie, alors exécuter certaines instructions.
  if (lumigameScrollTextFinished())
  {
    // Définit cette variable pour qu’elle soit égale à la valeur de l’entrée.
    phase = PHASE_EXIT;
  }
}

void jeu_vite_vite_start()
{
  // Initialise la communication série au débit en bauds donné. Placer dans un bloc 'setup' pour l'exécuter une seule fois au démarrage.
  Serial.begin(115200);
  // Affiche une valeur sur le port série. 'print line' (println) ajoute un saut de ligne final.
  Serial.println("jeu 1 : Début");
  // Définit cette variable pour qu’elle soit égale à la valeur de l’entrée.
  phase = PHASE_BOUCLE;
  // Met les 32 LED à la même couleur. Prend effet au prochain tour de loop().
  setAllLeds(CRGB::Black);
  // Essaie toutes les positions de bouton dans un ordre aléatoire, en exposant chaque candidate via une variable. « valide si » est une expression booléenne qui décide si elle est retenue (vrai par défaut si laissé vide). La première position valide déclenche « si trouvée » ; si aucune des 32 positions n'est valide, c'est « si aucune trouvée » qui s'exécute.
  {
    uint8_t candidates[NUM_BUTTONS];
    shuffledPositions(candidates);
    bool found = false;
    for (uint8_t idx = 0; idx < NUM_BUTTONS && !found; idx++)
    {
      uint8_t position = candidates[idx];
      bool valid = (true);
      if (valid)
      {
        found = true;
        // Définit cette variable pour qu’elle soit égale à la valeur de l’entrée.
        active_led = position;
      }
    }
    if (!found)
    {
    }
  }

  // Définit cette variable pour qu’elle soit égale à la valeur de l’entrée.
  vitesse = 5000;
  // (Re)démarre le minuteur INDEX (0-15) pour qu'il expire dans le nombre de millisecondes donné. Chaque index tourne indépendamment, donc plusieurs minuteurs peuvent être actifs en même temps.
  lumigameTimerSet(TIMER, vitesse);
  // Définit cette variable pour qu’elle soit égale à la valeur de l’entrée.
  point = 0;
  // Appelle une fonction.
  update_led();
}

uint8_t jeu_vite_vite_loop()
{
  // Affiche une valeur sur le port série. 'print line' (println) ajoute un saut de ligne final.
  Serial.println("jeu 1 : Boucle");
  // Affiche une valeur sur le port série. 'print line' (println) ajoute un saut de ligne final.
  Serial.println(phase);
  // Aiguillage (switch) sur une expression. Utilisez [+] pour ajouter des cas et [−] pour les supprimer.
  switch (phase)
  {
  case PHASE_BOUCLE:
    // Appelle une fonction.
    boucle();
    break;
  case PHASE_GAME_OVER:
    // Appelle une fonction.
    game_over();
    break;
  case PHASE_SCORE:
    // Appelle une fonction.
    score();
    break;
  case PHASE_EXIT:
    // Termine immédiatement la partie en cours et revient au menu. À placer dans le bloc boucle d'un jeu.
    return -1;
    break;
  }
  return 0;
}

void jeu_vite_vite_stop()
{
}

// End of helper functions
