// This code has been automatically generated by Maker Block Studio.
// Changes are overwritten whenever the blocks are edited.
// Last generated: 2026-08-03 19:26:50 UTC

// Includes
#include <Arduino.h>
#include "lumigame.h"
// End of includes

// Global declarations
extern void jeu1_start();
extern uint8_t jeu1_loop();
extern void jeu1_stop();
// End of global declarations

// Initialization code
void setup()
{
  lumigameInit();
  // Enregistre un jeu. Le fichier du jeu doit définir les fonctions <id>_start(), <id>_loop() et <id>_stop() (par ex. avec des blocs de fonction "à faire"). <id>_loop() doit retourner une valeur non nulle quand la partie est terminée, pour revenir au menu. À placer dans le bloc de configuration LumiGame.
  addGame(jeu1_start, jeu1_loop, jeu1_stop);
}
// End of initialization code

// Forever running code
void loop()
{
  // Initialise l'I2C et les deux extenseurs de boutons TCA9555, puis enregistre chaque bloc "ajouter le jeu" placé à l'intérieur. Pilote aussi loop() : exécute le jeu en cours s'il y en a un, sinon le menu. À placer une seule fois sur le canevas.
  lumigameLoop();
}
// End of forever running code
